name:                l2b2l
version:             0.1.0.0
github:              "amkhlv/l2b2l"
license:             BSD3
author:              "Andrei Mikhailov"
maintainer:          "amkhlv@gmail.com"
copyright:           "2017 - 2019 Andrei Mikhailov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/l2b2l#readme>

dependencies:
    - base >= 4.7 && < 5
    - directory
    - text
    - parsec
    - HaTeX
    - wl-pprint-extras
    - ansi-terminal
    - optparse-applicative
    - tagsoup
    - ansi-terminal
    - hxt

library:
  source-dirs: src

executables:
  l2b:
    main:                L2B.hs
    source-dirs:         app
    ghc-options:
      - -main-is L2B
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
    - l2b2l
  b2l:
    main:                B2L.hs
    source-dirs:         app
    ghc-options:
      - -main-is B2L
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - l2b2l
  bystro-toc:
    main:               BystroToc.hs
    source-dirs:        app
    ghc-options:
      - -main-is BystroToc
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - l2b2l

tests:
  l2b2l-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - l2b2l
